### ISSUE TITLE
pngfun not available

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nwfsc-assess/nwfscDiag#1]
The call to `pngfun()` on this line https://github.com/nwfsc-assess/nwfscDiag/blob/master/R/jitter_wrapper.R#L68
caused the following error after 100 jitters
```
Error in pngfun(wd = jitter_dir, file = paste0("Jitter_", model_settings$jitter_fraction,  (from jitter_wrapper.R#68) : 
  could not find function "pngfun"
```
@kellijohnson-NOAA suggested in issue https://github.com/r4ss/r4ss/issues/299 over a year ago that `pngfun` should be available in r4ss outside of the individual functions (though not necessarily exported) , but it isn't currently. I'm happy to implement that change in r4ss or `pngfun()` could just be added to `nwfscDiag` somewhere.

**Comment by chantelwetzel-noaa** [comment]
The pngfun() that is being used is apart of the HandyCode package which should have been loaded upon package installation.  Can you see if that package is available in your workspace?  I may need to modify this in the Descriptions file.

**Comment by chantelwetzel-noaa** [comment]
I just made a change that should avoid this issue.  Can you re-install the package?  Thanks @iantaylor-NOAA  for finding this issue.

**Comment by kellijohnson-NOAA** [comment]
Might also want to use HandyCode::pngfun() to make things clear. Though if this is the only function that we are using from that package, I think it would be better to have it as an exported function of r4ss give that we already install that package.

**Comment by chantelwetzel-noaa** [comment]
I have made the corrections suggested by @kellijohnson-NOAA of specifying it as HandyCode::pngfun() for the moment.  There are additional functions in this package that I often use for writing csv files to be used in my assessment template.  I have not incorporated any of them at this moment but may depending upon table feedback.  If people are satisfied with the created csv files as is then I think this should be changed to be a dependent of the r4ss package. I am going to leave this issue open so we can revisit this.

**Comment by owenhamel** [comment]
In: man/get_settings_profile.Rd:
The descriptions here may be accurate, but it is far from intuitive. It is not immediately clear that “relative” is simply “additive” to the base value, nor that “multiplier” is actual multiplying by either one minus or one plus the value given, dependent if it is low or high (note that alternative interpretations are not needed for the “real” or “relative” cases). I would suggest using “additive” and “actual” (since all the numbers you are using are real, as opposed to imaginary). I would also suggest that if you are going to use “multiplier”, have the input be the actual multipliers (e.g. 0.6, 1.4). That would be the most intuitive approach. Otherwise use “relative multiplier” (or perhaps you can improve upon that) to describe a proportional decrease or increase, in which the inputs would indicate the direction (e.g. -0.4, 0.4). 
In addition, in the description, x% is used to refer to numbers that are proportions rather than percents.
